#!/bin/sh

# 修改基本设置
uci set system.@system[0].hostname='OpenWrt-GXNAS'
uci set system.@system[0].zonename='Asia/Shanghai'
uci set system.@system[0].timezone='CST-8'
uci -q delete system.ntp.server
uci add_list system.ntp.server='ntp.aliyun.com'
uci add_list system.ntp.server='time1.cloud.tencent.com'
uci add_list system.ntp.server='time.apple.com'
uci add_list system.ntp.server='time.windows.com'
uci commit system

# iStore 前端语言[让 i18n.translate("istore_vue_lang") 返回 zh-cn]
mkdir -p /usr/lib/lua/luci/i18n
cat > /tmp/istore_vue_lang.zh-cn.lua << 'EOF'
istore_vue_lang = "zh-cn"
EOF

# ========== Netdata 强制启用 ==========
[ -f /etc/config/netdata ] || touch /etc/config/netdata
uci -q batch <<EOF
set netdata.netdata=netdata
set netdata.netdata.enabled='1'
set netdata.netdata.port='19999'
commit netdata
EOF

[ -f /etc/init.d/netdata ] && {
    chmod +x /etc/init.d/netdata
    /etc/init.d/netdata enable
    /etc/init.d/netdata start
}

# TurboACC 默认启用 BBR
if [ -f /etc/config/turboacc ]; then
    uci -q set turboacc.config.tcpcca='bbr'
    uci -q commit turboacc
    /etc/init.d/turboacc restart >/dev/null 2>&1
fi

exit 0
