#!/bin/sh

# 修改基本设置
uci set system.@system[0].hostname='OpenWrt-GXNAS'
uci set system.@system[0].zonename='Asia/Shanghai'
uci set system.@system[0].timezone='CST-8'
uci -q delete system.ntp.server
uci add_list system.ntp.server='ntp.aliyun.com'
uci add_list system.ntp.server='time1.cloud.tencent.com'
uci add_list system.ntp.server='time.apple.com'
uci add_list system.ntp.server='time.windows.com'
uci commit system

# 强制 iStore 前端显示中文
if [ -f /www/luci-static/istore/i18n/zh-cn.json ]; then
    sed 's/"zh-cn":/"en":/' /www/luci-static/istore/i18n/zh-cn.json > /tmp/en-forced.json 2>/dev/null
    [ -s /tmp/en-forced.json ] && mv /tmp/en-forced.json /www/luci-static/istore/i18n/en.json
fi

# ========== Netdata 强制启用 ==========
[ -f /etc/config/netdata ] || touch /etc/config/netdata
uci -q batch <<EOF
set netdata.netdata=netdata
set netdata.netdata.enabled='1'
set netdata.netdata.port='19999'
commit netdata
EOF

[ -f /etc/init.d/netdata ] && {
    chmod +x /etc/init.d/netdata
    /etc/init.d/netdata enable
    /etc/init.d/netdata start
}

# TurboACC 默认启用 BBR
if [ -f /etc/config/turboacc ]; then
    uci -q set turboacc.config.tcpcca='bbr'
    uci -q commit turboacc
    /etc/init.d/turboacc restart >/dev/null 2>&1
fi

exit 0
